spring:
  application:
    name: log-analysis

  # PostgreSQL Database Configuration
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/loki_logs?currentSchema=aidt}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: aidt
    database-platform: org.hibernate.dialect.PostgreSQLDialect
